language: java
jdk:
  - openjdk8
branches:
  only:
  - master
  - dev
jobs:
  include:
    - stage: test
      script: ./gradlew test
    - stage: deploy
      if: branch = main
      deploy:
        provider: heroku
        api-key:
          secure: $HEROKU_API_KEY
        app: digimov-test-1